# This environment is whats used for development of this repo.
name: seoul-bikeshare
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9.7
  - pandas==1.3.4
  - sqlalchemy==1.4.17
  - psycopg2==2.9.2
  - matplotlib==3.5.1
  - scikit-learn==1.0.2
  - pip
  - pip: